---
driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false

provisioner:
    name                  : ansible_push
    verbose               : "vvvv"
    ansible_config        : "test/ansible.cfg"
    idempotency_test      : True
    diff                  : True
    sudo                  : <%= if ENV['TRAVIS'] then 'True' else 'False' end  %>
    raw_arguments         : <%= if ENV['TRAVIS'] then '-c local' else '' end %>
    extra_vars            : { 'kitchen_connection': '<%= if ENV["TRAVIS"] then "local" else "smart" end %>', 'kitchen_hosts': '<%= if ENV["TRAVIS"] then "localhost" else "all" end %>' }

platforms:
 - name                   : ubuntu10404-v2.0
   driver_config          :
     image                : quay.io/hellofresh/kitchen-base
     platform             : ubuntu
   provisioner            :
     ansible_playbook_bin : "$(ansible-version path v2)ansible-playbook"

suites:
  - name                  : user
    provisioner           :
        playbook          : "test/integration/user/user.yml"

  - name                  : directory
    provisioner           :
        playbook          : "test/integration/directory/directory.yml"

  - name                  : resolver_git
    provisioner           :
        playbook          : "test/integration/resolver_git/resolver_git.yml"

  - name                  : resolver_s3_hash
    provisioner           :
        playbook          : "test/integration/resolver_s3_hash/resolver_s3_hash.yml"

  - name                  : resolver_s3_file
    provisioner           :
        playbook          : "test/integration/resolver_s3_file/resolver_s3_file.yml"

  - name                  : delete_old_deployment
    provisioner           :
        playbook          : "test/integration/delete_old_deployment/delete_old_deployment.yml"

  - name                  : fastcgi_parm
    provisioner           :
        playbook          : "test/integration/fastcgi_parm/fastcgi_parm.yml"

  - name                  : shell_vars
    provisioner           :
        playbook          : "test/integration/shell_vars/shell_vars.yml"

  - name                  : custom_config
    provisioner           :
        playbook          : "test/integration/custom_config/custom_config.yml"

  - name                  : dotenv
    provisioner           :
        playbook          : "test/integration/dotenv/dotenv.yml"

  - name                  : yaml_vars
    provisioner           :
        playbook          : "test/integration/yaml_vars/yaml_vars.yml"
