---
language: python
python: "2.7"
services:
  - docker

env:
  - KITCHEN_TEST="user"
  - KITCHEN_TEST="directory"
  - KITCHEN_TEST="resolver-git"
  - KITCHEN_TEST="resolver-s3-hash"
  - KITCHEN_TEST="resolver-s3-file"
  - KITCHEN_TEST="delete-old-deployment"
  - KITCHEN_TEST="fastcgi-parm"
  - KITCHEN_TEST="shell-vars"
  - KITCHEN_TEST="dotenv"
  - KITCHEN_TEST="custom-config"
  - KITCHEN_TEST="yaml-vars"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler
  # Get ansible install
  - curl -s https://raw.githubusercontent.com/AutomationWithAnsible/ansible-setup/master/example/travis-install -o /tmp/travis-ansible-setup.sh

install:
  - bash /tmp/travis-ansible-setup.sh
  - bundle install

script:
    - ansible --version
    - export TRAVIS=True
    - bundle exec kitchen test $KITCHEN_TEST

after_success:
    - echo "Success"
