---

- name: current version | Create current symlink
  file: 
    src="{{ deployment_dir_work }}"
    dest="{{ deployment_dir_current }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="0755"
    state="link"
  register: symlink_update
  notify:
   - restart app

- name: current version | Create deployment date file
  copy:
    content=""
    dest="{{ deployment_dir_current }}/{{ current_date.stdout }}.deployment.date"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
  when: symlink_update.changed