---

- name: directory structure | Get current date
  shell: date +"%Y-%m-%d_%H_%M"
  changed_when: False
  register: current_date

- name: directory structure | Ensure home dir is present and ensure right permissions
  file:
    path="{{ deployment_user_home }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_dir_perm }}"
    state="directory"
  notify:
     - restart app

- name: directory structure | Ensure work dir is present and ensure right permissions
  file:
    path="{{ deployment_dir_work }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_dir_perm }}"
    state="directory"
  notify:
     - restart app

- name: directory structure | Ensure extra dirs are present and ensure right permissions
  file: 
    path="{{ item }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_dir_perm }}"
    state="directory"
  when: deployment_extra_dirs != "none"
  with_items: deployment_extra_dirs
  notify:
     - restart app

- name: directory structure | Check extra files stat
  stat: 
    path="{{ item }}"
  register: deployment_extra_files_stat
  when: deployment_extra_files != "none"
  with_items: deployment_extra_files

- name: directory structure | Set extra files stat to []
  set_fact:
      deployment_extra_files_stat_exists: []
  when: deployment_extra_files == "none"

- name: directory structure | Set extra files stat to []
  set_fact:
      deployment_extra_files_stat_exists: "{{ deployment_extra_files_stat.results | selectattr('stat.exists', 'equalto', False) | list | default([]) }}"
  when: deployment_extra_files != "none"

- name: directory structure | Ensure extra files are present and ensure right permissions
  file: 
    dest="{{ item.item }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_file_perm }}"
    state="touch"
  when: deployment_extra_files != "none" 
  with_items: deployment_extra_files_stat_exists
  notify:
     - restart app
