---
# Deploy from git specific branch or hash or tag 
# Directory shoud use git hash/tag
# Inital deployment

- include: resolver/main.yml
- include: config/main.yml
- include: cron/main.yml
  when: deployment_cron_jobs != 'none' 

