---

  # Maintain old path behaviour for v1 
- name: Set path for V1
  set_fact:
    path_for_template: "../../templates/"
  when: ansible_version.major == 1

- name: main | Check if first boot file exists
  stat:
    path="{{ deployment_guard_file }}"
  register: deployment_guard

- include: user.yml
  when: (not deployment_guard.stat.exists or deployment_force)

- include: directory-structure.yml
  when: deployment_dir_structure and not deployment_guard.stat.exists or deployment_force

- include: resolver/main.yml
  when: not deployment_guard.stat.exists or deployment_force

- include: dependency/main.yml
  when: not deployment_guard.stat.exists or deployment_force

- include: config/main.yml
  when: not deployment_guard.stat.exists or deployment_force

- include: cron.yml
  when: not deployment_guard.stat.exists or deployment_force

- include: current-version.yml
  when: (not deployment_guard.stat.exists or deployment_force) and deployment_resolver != 'none'

- name: main | Touch file guard
  copy:
    content=""
    dest="{{ deployment_guard_file }}"
  when: not deployment_guard.stat.exists or deployment_force

- name: main | Flush handler
  meta: flush_handlers

- name: main | Include post deployment
  include: post-deployment/main.yml
  when: run_post_deployment is defined and run_post_deployment