---

- name: dependency | composer | Run composer
  composer:
  args: "{{ deployment_dependency_composer_args }}"
  become_user: "{{ deployment_composer_user }}"
  register: composer_output
  ignore_errors: True
  notify:
     - restart app