---

- name: config | dotenv | write dotenv variables file
  template: 
    src="{{ path_for_template }}dotenv.j2"
    dest="{{ deployment_config_dotenv_vars_dest }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_user }}"
    mode="{{ deployment_config_file_perm }}"
  notify:
     - restart app
