---

- name: config | ini | write ini variables file
  template: 
    src="{{ path_for_template }}inivars.ini.j2"
    dest="{{ deployment_config_ini_vars_dest }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_user }}"
    mode="{{ deployment_config_file_perm }}"
  notify:
     - restart app