---

- name: config | environment_variable | write environment variables to a single file
  template: 
    src="{{ path_for_template }}shell_environment.sh.j2"
    dest="{{ deployment_config_shell_vars_dest }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_config_file_perm }}"
  when: "deployment_config_shell_vars is mapping"
  notify:
     - restart app

- name: config | environment_variable | write environment variables to a multi files
  template: 
    src="{{ path_for_template }}shell_environment.sh.j2"
    dest="{{ item.dest }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_config_file_perm }}"
  with_items: deployment_config_shell_vars
  when: "deployment_config_shell_vars is not mapping"
  notify:
     - restart app


# - name: config | environment_variable | Source environment variables file in your profile
#   lineinfile: 
#       line="{{item}}"
#       insertbefore="BOF"
#       state="present"
#       create="yes"
#       mode="0644"
#       dest="{{ deployment_config_shell_profile }}"
#   with_items: 
#     - "source {{ deployment_config_shell_file }}"
#   when:
#   notify:
#      - restart app