---

- name: config | yaml | write yaml variables file
  template:
    src="{{ path_for_template }}yamlvars.j2"
    dest="{{ deployment_config_yaml_vars_dest }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_config_file_perm }}"
  when: "deployment_config_yaml_vars is mapping"
  notify:
     - restart app

- name: config | yaml | write yaml variables to a multi files
  template:
    src="{{ path_for_template }}yamlvars.j2"
    dest="{{ item.dest }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_config_file_perm }}"
  with_items: "{{ deployment_config_yaml_vars }}"
  when: "deployment_config_yaml_vars is not mapping"
  notify:
     - restart app
