---

- name: config | yaml | write yaml variables file
  template:
    src="{{ path_for_template }}yamlvars.j2"
    dest="{{ deployment_config_yaml_vars_dest }}"
    owner="{{ deployment_user }}"
    group="{{ deployment_user }}"
    mode="{{ deployment_config_file_perm }}"
  notify:
     - restart app
