---

- name: resolver | delete old deployments | Check and delete old deployments 
  delete_old_deployments: 
    path="{{ deployment_dir_base }}"
    keep_last="{{ deployment_keep_last }}"
    use_semantic_versioning="{{ deployment_use_semantic_versioning }}"
